🧹 update example with cnspec provisioner
mondoohq/packer-plugin-cnspec pull request #59
Opened 2022-12-08 13:41 UTC by chris-rock

2022-12-08 17:13 UTC, scottford-io requested changes
@chris-rock thanks for updating these. I think we should remove the platform-specific configs from the examples now that we use `cnspec` and those inputs only work when connected to Mondoo Platform. 

Also, I don't think we need the `mondoo_config_path` input anymore.

2022-12-08 17:13 UTC, scottford-io commented on examples/packer-aws/amazon-linux-2.json
>        "mondoo_config_path": "{{user `mondoo_config_path`}}",
do we still need this?

2022-12-08 17:13 UTC, scottford-io commented on examples/packer-aws/amazon-linux-2.pkr.hcl
>      mondoo_config_path = "${var.mondoo_config_path}"
I think we should remove these, and make the examples work without the platform. 

`asset_name` is a platform-only feature.

2022-12-08 17:13 UTC, scottford-io commented on examples/packer-aws/ubuntu-18.04.json
>        "mondoo_config_path": "{{user `mondoo_config_path`}}",
I don't think we need this anymore

2022-12-08 17:13 UTC, scottford-io commented on examples/packer-aws/ubuntu-20.04.json
>        "mondoo_config_path": "{{user `mondoo_config_path`}}",
We should remove this.

2022-12-11 11:18 UTC, chris-rock commented on examples/packer-aws/amazon-linux-2.json
>        "mondoo_config_path": "{{user `mondoo_config_path`}}",
I think we should remove this from default examples

2022-12-11 11:58 UTC, chris-rock commented
@scottford-io great suggestion. I removed `mondoo_config_path` from the examples since they are not required anymore.

2022-12-11 15:54 UTC, scottford-io approved these changes
Thanks @chris-rock !!! 👍

2022-12-11 15:54 UTC, merged